name: "Invalidate CloudFront distribution paths"
description: "Invalidate /* in CloudFront"
inputs:
  aws_cloudfront_distribution_id:
    description: "CloudFront Distribution ID"
    required: true
    default: ""
runs:
  using: "composite"
  steps:
    - name: Invalidate CloudFront distribution paths
      shell: bash
      env:
        AWS_CLOUDFRONT_DISTRIBUTION_ID: ${{ inputs.aws_cloudfront_distribution_id }}
      run: |
        aws cloudfront create-invalidation --distribution-id $AWS_CLOUDFRONT_DISTRIBUTION_ID --paths "/*"
        echo "### :arrows_counterclockwise: Issued CloudFront invalidation" >> $GITHUB_STEP_SUMMARY
